[project]
name = "niji-python"
version = "0.1.0"
description = "Python component for niji"
requires-python = "==3.12.*"
dependencies = [
    "fastembed",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
